### ISSUE TITLE
Upload Image error handling

### ISSUE THREAD

**Issue by Wadjetz** [Cumulus-Cloud/cumulus#172]
<img width="820" alt="capture d ecran 2018-04-22 a 12 04 59" src="https://user-images.githubusercontent.com/2094791/39093987-d7a19d18-4628-11e8-9143-35d1c1f838f7.png">

**Comment by Wadjetz** [comment]
ça arrive si tu upload une image qui n'est pas une (avec un mauvaise extension)

**Comment by Vuzi** [comment]
Fixed by #176
